# Generated by Django 4.1.2 on 2023-04-04 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prasanthapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
